
- name: install nginx prerequisite
  ansible.builtin.apt:
    name:
    - curl
    - gnupg2
    - ca-certificates
    - ubuntu-keyring
    update_cache: yes

- name: setup apt repository for nginx
  ansible.builtin.shell: ./nginx_installation.sh
  args:
    chdir: /vagrant/nginx

- name: install nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: yes
    allow_unauthenticated: yes

- name: set nginx conf
  ansible.builtin.copy:
    src: /vagrant/nginx/default.conf
    dest: /etc/nginx/conf.d/default.conf
    remote_src: yes

- name: copy nginx arp setting
  ansible.builtin.copy:
    src: /vagrant/nginx/realserver.sh
    dest: /etc/init.d/realserver.sh
    mode: 777
    remote_src: yes

- name: restart nginx
  ansible.builtin.shell: ./realserver.sh
  args:
    chdir: /etc/init.d

- name: apply arp setting on start
  ansible.builtin.shell: ./autostart.sh
  args:
    chdir: /vagrant/nginx

- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: started

- name: install jdk for spring application
  ansible.builtin.shell: ./jdk_installation.sh
  args:
    chdir: /vagrant
